version: '3.9'
services:
  postgresDB:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data   
volumes:
  postgres-data: